TongjiPoly = GetOSMFootprint(".\Data\OSM\map.osm",24474429);
% gif图输出
iSimListGif = 1:10; gifFilename = './Figures/IMsim_T0_5.gif'; delayTime = 0.5;
iTplot = 12;
createIMGifFromSimulations(@(x)Plot_IM_Spatial(IM_mat_Mesh,lonVec,latVec, ...
    Tvec_Mesh,Capacity3D=Capacity3D, ...
    Mask=TongjiPoly,iTplot=iTplot,iSim=x), ...
    iSimListGif, gifFilename, delayTime);